title: Packaging your code
hero_image: images/banner.png
description: Packaging-your-code description
theme: red # possible values: blue, green, navy, orange, red, turquoise, violet, yellow
duration: 2
listed: false
ingredient: false
copyedit: false
version: 4
last_tested: 2018-06-08
steps: 
- title: Introduction
- title: Create your python package
- title: Creating a setup
- title: Installing
- title: Adding meta data
- title: "Challenge: Create your own"